/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";

interface FieldSVGs15Interface extends ethers.utils.Interface {
  functions: {
    "field_218(uint24[4])": FunctionFragment;
    "field_219(uint24[4])": FunctionFragment;
    "field_220(uint24[4])": FunctionFragment;
    "field_221(uint24[4])": FunctionFragment;
    "field_222(uint24[4])": FunctionFragment;
    "field_223(uint24[4])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "field_218",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "field_219",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "field_220",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "field_221",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "field_222",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "field_223",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;

  decodeFunctionResult(functionFragment: "field_218", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "field_219", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "field_220", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "field_221", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "field_222", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "field_223", data: BytesLike): Result;

  events: {};
}

export class FieldSVGs15 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FieldSVGs15Interface;

  functions: {
    field_218(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;

    field_219(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;

    field_220(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;

    field_221(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;

    field_222(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;

    field_223(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          fieldType: number;
          svgString: string;
        }
      ]
    >;
  };

  field_218(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  field_219(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  field_220(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  field_221(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  field_222(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  field_223(
    colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      fieldType: number;
      svgString: string;
    }
  >;

  callStatic: {
    field_218(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;

    field_219(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;

    field_220(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;

    field_221(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;

    field_222(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;

    field_223(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        fieldType: number;
        svgString: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    field_218(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    field_219(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    field_220(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    field_221(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    field_222(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    field_223(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    field_218(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    field_219(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    field_220(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    field_221(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    field_222(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    field_223(
      colors: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
