/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";

interface HardwareSVGs15Interface extends ethers.utils.Interface {
  functions: {
    "hardware_57()": FunctionFragment;
    "hardware_58()": FunctionFragment;
    "hardware_59()": FunctionFragment;
    "hardware_60()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "hardware_57",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_58",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_59",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_60",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "hardware_57",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hardware_58",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hardware_59",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hardware_60",
    data: BytesLike
  ): Result;

  events: {};
}

export class HardwareSVGs15 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HardwareSVGs15Interface;

  functions: {
    hardware_57(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_58(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_59(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_60(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;
  };

  hardware_57(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_58(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_59(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_60(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  callStatic: {
    hardware_57(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_58(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_59(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_60(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    hardware_57(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_58(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_59(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_60(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hardware_57(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_58(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_59(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_60(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
