/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";

interface HardwareSVGs1Interface extends ethers.utils.Interface {
  functions: {
    "hardware_0()": FunctionFragment;
    "hardware_1()": FunctionFragment;
    "hardware_2()": FunctionFragment;
    "hardware_3()": FunctionFragment;
    "hardware_4()": FunctionFragment;
    "hardware_5()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "hardware_0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardware_5",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "hardware_0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardware_1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardware_2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardware_3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardware_4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardware_5", data: BytesLike): Result;

  events: {};
}

export class HardwareSVGs1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HardwareSVGs1Interface;

  functions: {
    hardware_0(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_1(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_2(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_3(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_4(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;

    hardware_5(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, string] & {
          title: string;
          hardwareType: number;
          svgString: string;
        }
      ]
    >;
  };

  hardware_0(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_1(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_2(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_3(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_4(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  hardware_5(
    overrides?: CallOverrides
  ): Promise<
    [string, number, string] & {
      title: string;
      hardwareType: number;
      svgString: string;
    }
  >;

  callStatic: {
    hardware_0(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_1(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_2(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_3(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_4(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;

    hardware_5(
      overrides?: CallOverrides
    ): Promise<
      [string, number, string] & {
        title: string;
        hardwareType: number;
        svgString: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    hardware_0(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_1(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_2(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_3(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_4(overrides?: CallOverrides): Promise<BigNumber>;

    hardware_5(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hardware_0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_4(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardware_5(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
