/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface JoepegsCrowdfundHandlerInterface extends ethers.utils.Interface {
  functions: {
    "INTERFACE_ID_ERC1155()": FunctionFragment;
    "INTERFACE_ID_ERC721()": FunctionFragment;
    "enabledMethods(bytes4)": FunctionFragment;
    "handleCrowdfundExecution(address,address,address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC1155",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enabledMethods",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleCrowdfundExecution",
    values: [string, string, string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enabledMethods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleCrowdfundExecution",
    data: BytesLike
  ): Result;

  events: {};
}

export class JoepegsCrowdfundHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: JoepegsCrowdfundHandlerInterface;

  functions: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<[string]>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<[string]>;

    enabledMethods(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    handleCrowdfundExecution(
      crowdfundContract: string,
      assetContract: string,
      forumGroup: string,
      tokenId: BigNumberish,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;
  };

  INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

  INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

  enabledMethods(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  handleCrowdfundExecution(
    crowdfundContract: string,
    assetContract: string,
    forumGroup: string,
    tokenId: BigNumberish,
    payload: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string]>;

  callStatic: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

    enabledMethods(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleCrowdfundExecution(
      crowdfundContract: string,
      assetContract: string,
      forumGroup: string,
      tokenId: BigNumberish,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;
  };

  filters: {};

  estimateGas: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<BigNumber>;

    enabledMethods(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleCrowdfundExecution(
      crowdfundContract: string,
      assetContract: string,
      forumGroup: string,
      tokenId: BigNumberish,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    INTERFACE_ID_ERC1155(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC721(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    enabledMethods(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleCrowdfundExecution(
      crowdfundContract: string,
      assetContract: string,
      forumGroup: string,
      tokenId: BigNumberish,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
